### ISSUE TITLE
Check if expanding instructions in step 3 can be replaced by clicking the "expand all" button

### ISSUE THREAD

**Issue by liberforce** [giventofly/exportpwp#6]
There's an "expand all" button just on the left of the header row. Is this is achieving the same as what you're doing with code?
This might be simplified telling the user to click on that button.

**Comment by giventofly** [comment]
That button doesn't load every information, you would need to go slowly thru the page for the lazyload to catch on (I did try that button first when I started).

**Comment by liberforce** [comment]
Isn't that already the case? You specify:

> After everything is loaded/open

**Comment by liberforce** [comment]
Just trying to see if this can be directly put at the beginning of the main block of code, to have less manual steps.

**Comment by giventofly** [comment]
No, because using the button only expans the boxes but don't load them. You need to force the load of the lazyload elements thus the need for that step (and the same to expand teams).

**Comment by liberforce** [comment]
Ok, so is there a way to automatically detect when all the fields required are loaded, and proceed running the export code, so that only a single copy/paste is required?

**Comment by giventofly** [comment]
Would be need to check if all the POST requests have been answered successfully (never had to use/search for this). Would probably need to add some listeners somewhere, but like I said, never had to do anything similar to that (specially with code that I don't "control") so don't know where to start

**Comment by liberforce** [comment]
I've never coded in javascript more than an « hello world », so that would need a web person.

**Comment by giventofly** [comment]
Will close this issue and also give a quick lock if this is a trivial thing to implement (I'm assuming it's not).

**Comment by liberforce** [comment]
Keeping the issue open would allow other people to notice help is needed. I recommend you to let the bugs open and use a triaging tag, like `help-wanted`.

**Comment by liberforce** [comment]
Sure that's code with a single month of expected lifespan, but the smoother the process is, the better. People with a very big history but not fluent with technology will benefit from a process as simple as possible.

**Comment by zendamacf** [comment]
I think the options here might be:
- Overriding their `ToggleHistoryItemExpansion` (executed when expanding/collapsing) function so that you can keep track of the items being finished. Also `DisplayTeamOpponents` for team events.
- Using `setTimeout` to check if they're all expanded every X amount of time. You could check if the number of `.EventSummary` existing matches the count of `a.Expand`. That'd let you know once the base event data has loaded. .

For reference, both `ToggleHistoryItemExpansion` and `DisplayTeamOpponents` are defined in
https://www.wizards.com/Magic/PlaneswalkerPoints/Content/Scripts/PlaneswalkerPoints.js

Sidenote: `DisplayTeamOpponents` looks like it's just hiding/showing content, rather than fetching data via AJAX, so it *might* not be necessary to actually expand that?

**Comment by giventofly** [comment]
> Sidenote: DisplayTeamOpponents looks like it's just hiding/showing content, rather than fetching data via AJAX, so it might not be necessary to actually expand that?

I don't have any of those in my historic so I can't confirm it, assumed it was the case. Until confirmation I think it's best to keep it that way. If you have those events and can confirm, that step can be removed.
___

Good suggestion for the intervals, will see if can do something quick for that because I'm kind short of time available.

EDIT: checked the code, correct the team only shows/hides the info. Working on the auto-check, should be done in the next few moments.
